<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>8. From framework to strategy: implementation and live evidence – RR Strategy Research</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-7f8f88aac4f3542376d5c11b86a4c14d.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">RR Strategy Research</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./01_markets_prices_expectations.html"> 
<span class="menu-text">1. Prices &amp; Expectations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./02_signals_forecasting_outperformance.html"> 
<span class="menu-text">2. Signals</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./03_return_sources_factor_structure.html"> 
<span class="menu-text">3. Return Sources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./04_portfolio_construction.html"> 
<span class="menu-text">4. Portfolio Construction</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./05_expected_returns.html"> 
<span class="menu-text">5. Expected Returns</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./06_core_allocation_active_programs.html"> 
<span class="menu-text">6. Core Allocation</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./07_strategy_implementation.html" aria-current="page"> 
<span class="menu-text">7. Strategy</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contents</h2>
   
  <ul>
  <li><a href="#the-instrument-universe-and-why-these-six-futures" id="toc-the-instrument-universe-and-why-these-six-futures" class="nav-link active" data-scroll-target="#the-instrument-universe-and-why-these-six-futures">The instrument universe and why these six futures</a></li>
  <li><a href="#strategy-architecture" id="toc-strategy-architecture" class="nav-link" data-scroll-target="#strategy-architecture">Strategy architecture</a></li>
  <li><a href="#backtest-results" id="toc-backtest-results" class="nav-link" data-scroll-target="#backtest-results">Backtest results</a></li>
  <li><a href="#parameter-robustness" id="toc-parameter-robustness" class="nav-link" data-scroll-target="#parameter-robustness">Parameter robustness</a></li>
  <li><a href="#regime-decomposition" id="toc-regime-decomposition" class="nav-link" data-scroll-target="#regime-decomposition">Regime decomposition</a></li>
  <li><a href="#factor-attribution" id="toc-factor-attribution" class="nav-link" data-scroll-target="#factor-attribution">Factor attribution</a></li>
  <li><a href="#live-deployment-darwinex-zero-evidence" id="toc-live-deployment-darwinex-zero-evidence" class="nav-link" data-scroll-target="#live-deployment-darwinex-zero-evidence">Live deployment: Darwinex Zero evidence</a></li>
  <li><a href="#what-would-constitute-evidence-of-strategy-failure" id="toc-what-would-constitute-evidence-of-strategy-failure" class="nav-link" data-scroll-target="#what-would-constitute-evidence-of-strategy-failure">What would constitute evidence of strategy failure</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">8. From framework to strategy: implementation and live evidence</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The seven preceding sections built a framework for evaluating investment return sources, constructing portfolios, and assessing whether active programs justify their place alongside a passive core. This section applies that framework directly to a specific systematic strategy — not as an illustration, but as the strategy this research was written to support.</p>
<p>The standards the framework establishes are demanding. A strategy’s return sources should be identifiable. Its portfolio contribution should be demonstrable beyond standalone Sharpe. Its implementation should be honest about costs, capacity, and signal decay. It should have been stress-tested against the regimes where its logic is most likely to fail. The analysis in this section applies each of those standards in turn.</p>
<section id="the-instrument-universe-and-why-these-six-futures" class="level2">
<h2 class="anchored" data-anchor-id="the-instrument-universe-and-why-these-six-futures">The instrument universe and why these six futures</h2>
<p>The strategy trades six liquid futures contracts: ES (S&amp;P 500), NQ (Nasdaq-100), RTY (Russell 2000), GC (Gold), SI (Silver), and ZN (10-year Treasury). The selection was driven by three criteria operating simultaneously.</p>
<p>The first is liquidity. All six instruments trade on regulated U.S. exchanges with deep intraday markets, tight spreads, and sufficient open interest to execute the strategy’s position sizes without material market impact. This is not a trivial constraint — futures markets vary enormously in liquidity, and selecting instruments at the margin of acceptable liquidity introduces execution risk that backtests systematically underestimate.</p>
<p>The second is asset class breadth within a long-term portfolio context. The universe spans U.S. equity (three contracts covering large-cap growth, broad large-cap, and small-cap), real assets (gold and silver), and fixed income (ten-year Treasury duration). Each represents a distinct economic exposure that would belong in a considered long-term allocation. This criterion deliberately excluded highly correlated instruments — adding multiple currency pairs, commodity sub-sectors, or short-term interest rate contracts would have increased nominal breadth without adding genuine diversification. The correlation structure of the six instruments is designed to give the IR-based rotation signal meaningful variation to exploit.</p>
<p>The third is availability on the Darwinex Zero platform, which is the live deployment environment for the strategy. The instrument set reflects what is practically tradeable within that infrastructure. As alternative platforms and data sources become available — particularly professional futures data providers with clean back-adjustment — the universe will be reviewed. The current six represent the intersection of what is liquid, structurally sensible, and operationally accessible.</p>
</section>
<section id="strategy-architecture" class="level2">
<h2 class="anchored" data-anchor-id="strategy-architecture">Strategy architecture</h2>
<p>The strategy is a systematic multi-asset allocator built around two signal layers operating at different frequencies.</p>
<p>The <strong>volatility-targeting layer</strong> computes a rolling Sortino ratio for each asset using a 252-day lookback window. The ratio is then z-scored over the same window to produce a normalized signal bounded by the tanh function. This signal drives the target downside volatility for each asset, ranging between 10 and 20 percent annualized. Assets with strongly positive Sortino z-scores are allocated higher target volatility; assets with negative or weakly positive scores receive lower target volatility. The practical effect is that leverage increases when recent risk-adjusted performance is strong and decreases when it deteriorates. This is the primary mechanism for dynamic beta management discussed in the factor attribution section.</p>
<p>The <strong>tactical allocation layer</strong> computes a rolling information ratio of each alternative asset versus ES over a 252-day window. The IR measures how consistently the alternative has outperformed the equity core on a risk-adjusted basis. High-IR alternatives receive a larger weight in the tactical sleeve, which can represent up to 50 percent of the total portfolio. Low-IR alternatives receive zero or minimal allocation. The ES core always maintains a residual weight equal to one minus the sum of alternative weights, ensuring the strategy remains net long equity at all times.</p>
<p>The two layers combine to produce a daily target allocation that is then smoothed with a 10-day exponential moving average to reduce unnecessary turnover. A 10 percent notional no-trade band prevents rebalancing when the position drift is small relative to the signal change, reducing commission drag without meaningfully delaying regime transitions.</p>
<p><strong>The connection to the framework is direct.</strong> Section 4’s return source taxonomy explains what the strategy harvests: equity risk premium from the ES core, real asset carry from gold and silver, and duration from ZN in risk-off environments. Section 5’s portfolio construction principles explain why the 50 percent tactical sleeve cap was chosen — the position sizing table showed that above this level the drawdown cost exceeds the return benefit. Section 6’s regime conditioning explains why the signals use 12-month lookback windows — they are designed to identify sustained performance differences, not short-term noise. Section 7’s cost hierarchy explains where the strategy sits in a broader portfolio: as a carefully justified active program that can sit alongside a simpler passive core, not as a replacement for one.</p>
</section>
<section id="backtest-results" class="level2">
<h2 class="anchored" data-anchor-id="backtest-results">Backtest results</h2>
<p>The baseline strategy was backtested from 2002 to March 2026 using Yahoo Finance continuous futures data with $5 per contract commission. All signals are lagged one day to prevent look-ahead bias. The common analysis start date is 2003-08-18, reflecting the warm-up period required for the longest signal windows to initialize.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th>Strategy</th>
<th>ES benchmark</th>
<th>ES-only (levered)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total return</td>
<td>3,699%</td>
<td>601%</td>
<td>2,250%</td>
</tr>
<tr class="even">
<td>CAGR</td>
<td>16.8%</td>
<td>8.6%</td>
<td>14.3%</td>
</tr>
<tr class="odd">
<td>Ann. volatility</td>
<td>22.3%</td>
<td>19.0%</td>
<td>23.4%</td>
</tr>
<tr class="even">
<td>Sharpe ratio</td>
<td><strong>0.807</strong></td>
<td>0.530</td>
<td>0.689</td>
</tr>
<tr class="odd">
<td>Sortino ratio</td>
<td><strong>1.095</strong></td>
<td>0.745</td>
<td>0.936</td>
</tr>
<tr class="even">
<td>Max drawdown</td>
<td><strong>−30.2%</strong></td>
<td>−57.1%</td>
<td>−42.4%</td>
</tr>
</tbody>
</table>
<p>The strategy produces a Sharpe ratio of 0.807 and a Sortino ratio of 1.095 over the full backtest period, compared to 0.530 and 0.745 for the ES buy-and-hold benchmark. The maximum drawdown of −30.2% compares favorably to −57.1% for the benchmark and −42.4% for the levered ES-only alternative. The total return of 3,699% over 22 years reflects the combination of genuine return generation and the power of compounding over a long period.</p>
<p>The performance gap between the strategy and the ES benchmark is not primarily due to leverage — the ES-only levered alternative (which applies the same Sortino-based leverage but holds only ES) produces a CAGR of 14.3% and Sharpe of 0.689. The additional 2.5 percentage points of CAGR and 0.118 Sharpe points above the levered ES baseline reflect the value of tactical allocation across the alternative assets.</p>
</section>
<section id="parameter-robustness" class="level2">
<h2 class="anchored" data-anchor-id="parameter-robustness">Parameter robustness</h2>
<p>A strategy that performs well only at its exact design parameters is a backtest artifact rather than a robust investment program. The robustness analysis addresses this directly through two complementary methods.</p>
<p>The <strong>one-at-a-time sensitivity analysis</strong> tested each of the six key parameters — Sortino window, IR window, vol window, tactical sleeve cap, EMA smoothing span, and no-trade band — across five values ranging from −50% to +50% of the baseline. The baseline Sharpe of 0.807 was near the top of the distribution for four of the six parameters, with EMA span and no-trade band showing essentially no sensitivity to variation.</p>
<p>The <strong>Monte Carlo analysis</strong> used Latin Hypercube sampling to test 50 randomly chosen combinations across the full six-dimensional parameter space, with all combinations evaluated over the same common analysis start date to ensure a fair comparison. The corrected results show that 52% of combinations produced a Sharpe above 0.70 on a level playing field, with the baseline sitting at the 98th percentile of the distribution.</p>
<div id="c16112d8" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-3-output-1.png" width="883" height="448" class="figure-img"></p>
<figcaption>Distribution of Sharpe ratios across 50 randomly sampled parameter combinations. Common analysis start date: 2003-08-18. The baseline configuration (dashed black line, Sharpe 0.807) sits at the 98th percentile of the distribution. 52% of combinations exceed the 0.70 threshold. Source: Author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<p>The most important finding from the robustness analysis is the dominant role of the Sortino window. Shorter windows (126–189 days) consistently outperform longer windows (315–378 days) — the correlation between Sortino window length and Sharpe ratio across the Monte Carlo sample is −0.77. This suggests the 252-day baseline window may be slightly longer than optimal, and a 189-day window is a candidate for a future design revision pending out-of-sample confirmation from the live deployment.</p>
<div id="710d0e84" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-4-output-1.png" width="881" height="499" class="figure-img"></p>
<figcaption>Sharpe ratio distribution by parameter level across 50 Monte Carlo combinations. The Sortino window panel (top center) shows the clearest directional pattern — shorter windows produce higher Sharpe ratios. EMA span and no-trade band show negligible sensitivity. Source: Author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<div id="2447e898" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-5-output-1.png" width="595" height="499" class="figure-img"></p>
<figcaption>Monte Carlo equity paths — 50 parameter combinations evaluated over the common analysis period from 2003-08-18. Black = baseline. Color = Sharpe ratio (green = higher, red = lower). The 5th–95th percentile band is shaded blue. All combinations trend upward throughout the sample. Source: Author calculations.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="regime-decomposition" class="level2">
<h2 class="anchored" data-anchor-id="regime-decomposition">Regime decomposition</h2>
<p>The framework established in section 6 that return estimates should condition on the prevailing macro regime. The regime decomposition applies this principle to the backtest — classifying each trading day into one of four regimes using observable FRED data and evaluating the strategy’s performance within each.</p>
<p>The four regimes are defined as follows. Equity Bear takes priority: any day where the trailing 12-month S&amp;P 500 return falls below −10% or the VIX exceeds 30 is classified as Bear regardless of other conditions. Inflation applies when CPI year-on-year exceeds 4% and is rising on a three-month basis. Equity Bull applies when the trailing 12-month S&amp;P 500 return exceeds 15%. All remaining days are Neutral.</p>
<div id="cf79f1fb" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-6-output-1.png" width="614" height="499" class="figure-img"></p>
<figcaption>Macro regime classification across the backtest period, 2003–2026. Top panel: strategy equity curve with regime shading. Lower panels: the three regime indicators — S&amp;P 500 12-month return, VIX, and CPI year-on-year. Bear regime takes priority over all others. Source: FRED (SP500, VIXCLS, CPIAUCSL), author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 8%">
<col style="width: 14%">
<col style="width: 8%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Regime</th>
<th>Days</th>
<th>% Sample</th>
<th>CAGR</th>
<th>Sharpe</th>
<th>Max DD</th>
<th>Win rate</th>
<th>Avg ES wt</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Equity Bull</td>
<td>837</td>
<td>14.1%</td>
<td>+82.2%</td>
<td>3.27</td>
<td>−21.8%</td>
<td>58.9%</td>
<td>56.1%</td>
</tr>
<tr class="even">
<td>Equity Bear</td>
<td>657</td>
<td>11.0%</td>
<td>−39.1%</td>
<td>−2.03</td>
<td>−22.5%</td>
<td>46.9%</td>
<td>60.0%</td>
</tr>
<tr class="odd">
<td>Inflation</td>
<td>575</td>
<td>9.7%</td>
<td>+7.5%</td>
<td>0.34</td>
<td>−28.8%</td>
<td>53.2%</td>
<td>68.4%</td>
</tr>
<tr class="even">
<td>Neutral</td>
<td>3884</td>
<td>65.2%</td>
<td>+19.9%</td>
<td>0.90</td>
<td>−24.5%</td>
<td>56.9%</td>
<td>61.8%</td>
</tr>
</tbody>
</table>
<p>Three findings from this table deserve explicit acknowledgment.</p>
<p>The strategy earns exceptional returns in Equity Bull regimes — a Sharpe of 3.27 and CAGR of 82.2% during the 14% of days classified as Bull. These periods drive the majority of compounded long-run return alongside the 65% Neutral regime, which delivers a solid Sharpe of 0.90. Together these two regimes account for 79% of the sample and produce all the strategy’s positive contribution.</p>
<p>The strategy loses money in Equity Bear regimes, at an annualized rate of −39.1% and a Sharpe of −2.03. This is the primary weakness of the design. The allocation heatmap reveals the mechanism: during Bear periods the average ES weight is 60.0% — slightly higher than the 56.1% during Bull periods. The signal does not rotate away from equity quickly enough when conditions deteriorate. The Sortino z-score and IR signals are both backward-looking by design, and they require several months of sustained deterioration before they reduce exposure materially. In a sharp, rapid bear market — 2020 is the clearest example — the strategy experiences full equity drawdown before the signal has time to act.</p>
<div id="ed199a59" class="cell" data-execution_count="6">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-7-output-1.png" width="754" height="499" class="figure-img"></p>
<figcaption>Strategy performance statistics by macro regime: annualized CAGR, Sharpe ratio, maximum drawdown, and daily win rate. The Bear regime (red) shows severe losses; the Bull regime (blue) shows exceptional performance. Day counts and sample percentages are shown at the base of the CAGR bars. Source: FRED, author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<p>The Inflation regime result is mediocre but survivable — a 7.5% CAGR and 0.34 Sharpe. More concerning is the allocation pattern: during inflation periods the average ES weight rises to 68.4% while gold averages only 7.4%. This is the opposite of what an inflation-protection design would prescribe. The strategy has no explicit inflation hedge. Its gold allocation during inflation reflects only the IR signal’s backward-looking assessment of gold versus ES performance, which may lag actual inflation dynamics considerably.</p>
<div id="91887f67" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-8-output-1.png" width="883" height="387" class="figure-img"></p>
<figcaption>Average asset allocation by macro regime. Each cell shows the average signal weight for that asset during that regime. The ES weight is high across all regimes (56–68%), confirming the strategy’s primary equity character. Gold (GC) rises to 14% during Bear regimes but falls to 7.4% during Inflation — the strategy has no explicit inflation protection mechanism. Source: Author calculations.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="factor-attribution" class="level2">
<h2 class="anchored" data-anchor-id="factor-attribution">Factor attribution</h2>
<p>The factor attribution analysis decomposes the strategy’s daily returns against four systematic factors: market (ES=F daily returns), duration (ZN=F daily returns), momentum (UMD from the Ken French library), and gold (GC=F daily returns).</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Factor</th>
<th>Beta</th>
<th>T-statistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Market (ES)</td>
<td>0.79</td>
<td>69.6</td>
</tr>
<tr class="even">
<td>Gold (GC)</td>
<td>0.28</td>
<td>23.5</td>
</tr>
<tr class="odd">
<td>Duration (ZN)</td>
<td>0.10</td>
<td>2.7</td>
</tr>
<tr class="even">
<td>Momentum (UMD)</td>
<td>0.12</td>
<td>2.0</td>
</tr>
<tr class="odd">
<td><strong>Alpha</strong></td>
<td><strong>6.4% ann.</strong></td>
<td><strong>1.94</strong></td>
</tr>
<tr class="even">
<td><strong>R-squared</strong></td>
<td><strong>49.3%</strong></td>
<td></td>
</tr>
</tbody>
</table>
<p>The two statistically robust factor exposures are market (beta 0.79, t=69.6) and gold (beta 0.28, t=23.5). Duration and momentum are marginally significant but contribute negligibly to return attribution. The full-sample R-squared of 49.3% means roughly half the strategy’s daily return variance is explained by these four factors — the rolling R-squared averages 71.2%, suggesting the full-sample estimate is pulled down by structural breaks in factor relationships across different macro regimes.</p>
<div id="ec3e7a6d" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-9-output-1.png" width="883" height="390" class="figure-img"></p>
<figcaption>Left: full-sample factor loadings with t-statistics. Right: annualized return contribution of each factor (β × factor annual return). Market exposure contributes 8.2% and gold 3.7%; duration and momentum are negligible. The alpha contribution of 6.4% represents the tactical allocation value-add above a static long equity and gold position. Source: Ken French Data Library, Yahoo Finance, author calculations.</figcaption>
</figure>
</div>
</div>
</div>
<p>The annualized alpha of 6.4% carries a t-statistic of 1.94 — close to but below the conventional 2.0 threshold. Over a 22-year backtest with daily data, this is the mathematically expected result for a genuine alpha of this magnitude given the residual volatility. It is not proof of skill — no backtest of any practical length can provide that — but it is consistent with a strategy that generates incremental return above a static factor exposure through dynamic leverage and tactical rotation.</p>
<p>The rolling beta analysis reveals an important structural feature of the strategy. While the full-sample market beta is 0.79, the rolling 252-day beta ranges from 0.16 to 3.1 with a mean of 1.25. The strategy is a dynamic beta amplifier — increasing market exposure when the Sortino signal is strongly positive and reducing it when signals deteriorate. This is entirely consistent with the design but should be understood clearly: the strategy is not a market-neutral or low-beta program. It is a leveraged equity strategy that manages exposure dynamically around an average of approximately 1.25 times the equity market.</p>
<div id="63f8df6e" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="07_strategy_implementation_files/figure-html/cell-10-output-1.png" width="499" height="499" class="figure-img"></p>
<figcaption>Rolling 252-day factor betas. The market beta panel shows the widest range (0.16 to 3.1) — the strategy is a dynamic beta amplifier. The gold beta is persistently positive and relatively stable (0.0–0.6). Duration and momentum show no persistent direction. Source: Ken French Data Library, Yahoo Finance, author calculations.</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="live-deployment-darwinex-zero-evidence" class="level2">
<h2 class="anchored" data-anchor-id="live-deployment-darwinex-zero-evidence">Live deployment: Darwinex Zero evidence</h2>
<p>The strategy has been deployed live on Darwinex Zero under the ticker UJNU since 5 March 2026. At the time of writing the live track record is approximately eight weeks old — too short for any statistical inference about skill versus luck, but sufficient to confirm that the implementation is functioning as designed.</p>
<p>Darwinex Zero applies a VaR normalization filter to all strategy returns before publishing them as a DARWIN index. This filter standardizes the risk profile of the published track record to a target VaR of 6.5% per month, which means the published DARWIN returns will differ from the underlying strategy returns in proportion to how far the strategy’s actual volatility diverges from that target. Investors comparing the DARWIN performance to the backtest results presented in this document should account for this normalization. The underlying strategy’s volatility targeting mechanism operates independently of the DARWIN risk filter — the two are applied sequentially, with the strategy’s own risk management layer acting first and the platform filter acting second.</p>
<p>The live deployment serves three specific purposes in the context of this research framework.</p>
<p>First, it tests whether the signal logic produces positions consistent with the theoretical framework under actual market conditions. A strategy that generates signals in backtesting but produces nonsensical or unstable positions in live trading has an implementation flaw that no amount of backtest analysis can reveal. Eight weeks of live trading confirms that the position generation, order sizing, and rebalancing mechanics are working as designed.</p>
<p>Second, it begins the process of building a verified, third-party-audited track record that is independent of the backtest data. The Darwinex Zero platform provides trade-level verification and standardized performance metrics that carry more evidential weight with sophisticated allocators than any self-reported backtest. The path from the current early-stage deployment to a statistically meaningful live track record requires continued performance across varied market conditions — the regime classification framework developed in section 8.5 provides the diagnostic lens for interpreting that performance as it accumulates.</p>
<p>Third, it creates a real-time test of the robustness findings. The Monte Carlo analysis identified the Sortino window as the dominant parameter — shorter windows outperformed consistently. The live deployment uses the 252-day baseline. If live performance is significantly below the backtest level during periods the regime classification identifies as Neutral or Bull — when the strategy should be performing well — that is a signal worth investigating. If performance is below backtest level only during Bear or Inflation regimes, that is expected behavior consistent with the regime decomposition findings.</p>
<p>The live track record will be reported and updated in the connected Darwinex Zero performance page as it accumulates. The appropriate evaluation horizon for drawing any conclusions about strategy quality is a minimum of 24 months of live trading across at least two distinct macro regimes — a standard that the current deployment has not yet had the time to meet.</p>
</section>
<section id="what-would-constitute-evidence-of-strategy-failure" class="level2">
<h2 class="anchored" data-anchor-id="what-would-constitute-evidence-of-strategy-failure">What would constitute evidence of strategy failure</h2>
<p>The most important intellectual discipline in systematic strategy management is defining in advance what evidence would cause you to conclude that the strategy is not working — as opposed to going through a normal period of adverse conditions that the design already anticipates.</p>
<p>The strategy should be considered to be failing — rather than experiencing normal variance — if any of the following conditions are met over a sustained period of at least 12 months of live trading:</p>
<p><strong>Signal failure:</strong> The correlation between the Sortino z-score signal and subsequent 21-day returns falls to near zero or below across all assets simultaneously. If the core signal is providing no information, the dynamic leverage mechanism is adding noise rather than return. Normal signal degradation in individual assets during regime transitions is expected and not a failure signal.</p>
<p><strong>Implementation divergence:</strong> Live position sizes and allocation weights diverge systematically from what the backtest signal would prescribe by more than the no-trade band threshold. This would indicate an execution or data integrity problem rather than a strategy problem, but the consequence is the same — the live deployment is no longer an expression of the tested strategy.</p>
<p><strong>Regime-inconsistent underperformance:</strong> The strategy underperforms the ES benchmark during Neutral and Bull regimes — the two regimes where the design is intended to outperform. Bear and Inflation regime underperformance relative to the benchmark is expected and is not a failure signal. Neutral and Bull regime underperformance sustained for more than 12 months, after adjusting for the VaR normalization filter, would suggest the IR rotation signal is not adding value in the current market microstructure.</p>
<p><strong>Parameter decay:</strong> The Sortino window finding from the Monte Carlo analysis — that shorter windows consistently outperform — should be tested against the live data after 24 months. If the 252-day baseline continues to underperform the 189-day alternative in out-of-sample live trading, a parameter revision is warranted.</p>
<p>What should not be interpreted as evidence of failure: a single quarter of poor performance in any regime, underperformance relative to the ES benchmark during Bear regimes, or drawdowns consistent with the historical maximum drawdown profile. The strategy’s maximum historical drawdown is −30.2%. An investor who exits the strategy after a 25% drawdown has applied a stricter tolerance than the backtest warranted — and section 5’s path risk discussion explains precisely why that behavioral pattern destroys value even in strategies with genuine positive expected return.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>